// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NbaDashboard.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NbaDashboard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NbaDashboard.Core.Entities.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Arena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<bool>("Postseason")
                        .HasColumnType("boolean");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeRemaining")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VisitorScore")
                        .HasColumnType("integer");

                    b.Property<int>("VisitorTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("VisitorTeamId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JerseyNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.PlayerGameAdvanced", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AstPct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DefRating")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DrebPct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EfgPct")
                        .HasColumnType("numeric");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Minutes")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetRating")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OffRating")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OrebPct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Pace")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Pie")
                        .HasColumnType("numeric");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RebPct")
                        .HasColumnType("numeric");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TsPct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UsgPct")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("GameId", "PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerGameAdvanced");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.PlayerGameStats", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("Blocks")
                        .HasColumnType("integer");

                    b.Property<int>("DefensiveRebounds")
                        .HasColumnType("integer");

                    b.Property<decimal>("FieldGoalPct")
                        .HasColumnType("numeric");

                    b.Property<int>("FieldGoalsAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("FieldGoalsMade")
                        .HasColumnType("integer");

                    b.Property<decimal>("FreeThrowPct")
                        .HasColumnType("numeric");

                    b.Property<int>("FreeThrowsAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("FreeThrowsMade")
                        .HasColumnType("integer");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Minutes")
                        .HasColumnType("numeric");

                    b.Property<int>("OffensiveRebounds")
                        .HasColumnType("integer");

                    b.Property<int>("PersonalFouls")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PlusMinus")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Rebounds")
                        .HasColumnType("integer");

                    b.Property<string>("StartPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Steals")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThreePointPct")
                        .HasColumnType("numeric");

                    b.Property<int>("ThreePointersAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("ThreePointersMade")
                        .HasColumnType("integer");

                    b.Property<int>("Turnovers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("GameId", "PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerGameStats");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.PlayerHeat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ComputedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GamesSampled")
                        .HasColumnType("integer");

                    b.Property<decimal>("HeatScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetRatingAvg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PieAvg")
                        .HasColumnType("numeric");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PtsAvg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TsPctAvg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UsgPctAvg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ComputedDate", "PlayerId");

                    b.HasIndex("PlayerId", "ComputedDate")
                        .IsUnique();

                    b.ToTable("PlayerHeat");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.PlayerSeasonStats", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AstAvg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BlkAvg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Fg3Pct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FgPct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FtPct")
                        .HasColumnType("numeric");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinAvg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetRating")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Per")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Pie")
                        .HasColumnType("numeric");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PtsAvg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RebAvg")
                        .HasColumnType("numeric");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("StlAvg")
                        .HasColumnType("numeric");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ToAvg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TsPct")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UsgPct")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.HasIndex("PlayerId", "SeasonId", "TeamId")
                        .IsUnique();

                    b.ToTable("PlayerSeasonStats");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.StandingsSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AwayRecord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConfRank")
                        .HasColumnType("integer");

                    b.Property<decimal>("DefRating")
                        .HasColumnType("numeric");

                    b.Property<int>("DivRank")
                        .HasColumnType("integer");

                    b.Property<string>("HomeRecord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Last10")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<decimal>("NetRating")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OffRating")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Pace")
                        .HasColumnType("numeric");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Streak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<decimal>("WinPct")
                        .HasColumnType("numeric");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId", "SeasonId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("StandingsSnapshots");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.SyncState", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Conference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.Game", b =>
                {
                    b.HasOne("NbaDashboard.Core.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NbaDashboard.Core.Entities.Season", "Season")
                        .WithMany("Games")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NbaDashboard.Core.Entities.Team", "VisitorTeam")
                        .WithMany()
                        .HasForeignKey("VisitorTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");

                    b.Navigation("VisitorTeam");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.Player", b =>
                {
                    b.HasOne("NbaDashboard.Core.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.PlayerGameAdvanced", b =>
                {
                    b.HasOne("NbaDashboard.Core.Entities.Game", "Game")
                        .WithMany("PlayerGameAdvanced")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NbaDashboard.Core.Entities.Player", "Player")
                        .WithMany("GameAdvanced")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NbaDashboard.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.PlayerGameStats", b =>
                {
                    b.HasOne("NbaDashboard.Core.Entities.Game", "Game")
                        .WithMany("PlayerGameStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NbaDashboard.Core.Entities.Player", "Player")
                        .WithMany("GameStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NbaDashboard.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.PlayerHeat", b =>
                {
                    b.HasOne("NbaDashboard.Core.Entities.Player", "Player")
                        .WithMany("HeatScores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.PlayerSeasonStats", b =>
                {
                    b.HasOne("NbaDashboard.Core.Entities.Player", "Player")
                        .WithMany("SeasonStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NbaDashboard.Core.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NbaDashboard.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.StandingsSnapshot", b =>
                {
                    b.HasOne("NbaDashboard.Core.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NbaDashboard.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.Game", b =>
                {
                    b.Navigation("PlayerGameAdvanced");

                    b.Navigation("PlayerGameStats");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.Player", b =>
                {
                    b.Navigation("GameAdvanced");

                    b.Navigation("GameStats");

                    b.Navigation("HeatScores");

                    b.Navigation("SeasonStats");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.Season", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("NbaDashboard.Core.Entities.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
